[global]
charset = utf-8
max connections = 8
reverse lookup = no
log file = /dev/stdout
pid file = /var/run/rsyncd.pid

[world]
    path = /share
    comment = World directory sync
    read only = yes
    list = yes
    uid = 0
    gid = 0
    # auth users = rsyncuser
    # secrets file = /etc/rsyncd.secrets
    # hosts allow = 192.168.0.0/16
